wsi: /path/to/the/output/folder/of/main/tiling/tiler/level_n/
raw_path: /path/to/raw/wsi/data
table_data: /path/to/master/table.csv
batch_size: 16
dropout: 0.4
feature_depth: 512 
lr: 0.003
num_workers: 16
model_name: mhmc_layers
nb_tiles: 10
epochs: 2
target_name: target
ref_metric: loss

